CREATE TABLE IF NOT EXISTS LIVROS (
    ID INT AUTO_INCREMENT,
    TITULO  VARCHAR(255) NOT NULL,
    GENEROLITERARIO VARCHAR(255),
    DESCRICAO VARCHAR(255),
    PRECO DOUBLE,
   AUTOR VARCHAR(255),
   CLASSIFICACAOETARIA VARCHAR(255),
    PRIMARY KEY (ID)
);